name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  linting_and_testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: unit tests
        run: CI=true npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  run_deployment:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs: [linting_and_testing]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "chess-hooks"
          heroku_email: ${{ secrets.EMAIL }}
          healthcheck: "https://chess-hooks.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs: [run_deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: none
      - name: Bump packagejson major version
        run: npm version major
        if: ${{ contains(join(github.event.commits.*.message, ', '), '#major') }}
      - name : Bump package.json minor version
        run: npm version minor
        if: ${{ contains(join(github.event.commits.*.message, ', '), '#minor') }}
      - name: Bump package.json patch version
        run: |
          git config user.name "pablo-maff"
          git config user.password ${{ secrets.PASSWORD }}
          git remote set-url origin https://github.com/pablo-maff/Chess-Hooks.git
          npm version patch
          ls -la
          git add .
          git commit -m 'Update package.json version'
          git push
        if: ${{ contains(join(github.event.commits.*.message, ', '), '#patch') }}